/**
 * Pin entity types
 *
 * Pins are a polymorphic non-destructive "promote to top" marker. Pin owns
 * its target registry because not every pinnable entity uses the shared UUID
 * entity id convention (for example, models use UniqueModelId).
 */

import * as z from 'zod'

import { AssistantIdSchema } from './assistant'
import { EntityIdSchema } from './entityType'
import { UniqueModelIdSchema } from './model'
import { TopicIdSchema } from './topic'

export const PinTargetTypeSchema = z.enum(['assistant', 'topic', 'session', 'model'])
export type PinTargetType = z.infer<typeof PinTargetTypeSchema>

const AssistantPinTargetSchema = z.strictObject({
  entityType: z.literal('assistant'),
  entityId: AssistantIdSchema
})

const TopicPinTargetSchema = z.strictObject({
  entityType: z.literal('topic'),
  entityId: TopicIdSchema
})

const SessionPinTargetSchema = z.strictObject({
  entityType: z.literal('session'),
  entityId: EntityIdSchema
})

const ModelPinTargetSchema = z.strictObject({
  entityType: z.literal('model'),
  entityId: UniqueModelIdSchema
})

export const PinTargetSchema = z.discriminatedUnion('entityType', [
  AssistantPinTargetSchema,
  TopicPinTargetSchema,
  SessionPinTargetSchema,
  ModelPinTargetSchema
])
export type PinTarget = z.infer<typeof PinTargetSchema>

// ============================================================================
// Pin Entity
// ============================================================================

export const PinIdSchema = z.uuidv4()

const PinRowFields = {
  /** Pin ID (UUID v4, auto-generated by database) */
  id: PinIdSchema,
  /** Fractional-indexing order key within this entityType */
  orderKey: z.string().min(1),
  /** Creation timestamp (ISO string) */
  createdAt: z.iso.datetime(),
  /** Last update timestamp (ISO string) */
  updatedAt: z.iso.datetime()
} as const

/**
 * Complete Pin entity as returned by the API.
 */
export const PinSchema = z.discriminatedUnion('entityType', [
  AssistantPinTargetSchema.extend(PinRowFields),
  TopicPinTargetSchema.extend(PinRowFields),
  SessionPinTargetSchema.extend(PinRowFields),
  ModelPinTargetSchema.extend(PinRowFields)
])
export type Pin = z.infer<typeof PinSchema>
